In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

numpy merupakan library python digunakan untuk komputasi matriks.
matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.
pandas merupakan library python untuk mengimport data dari sumber luar

In [35]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

variabel dataset yang diisi dengan function dari pandas yaitu read_csv (membaca data.csv yang sudah di upload pada repository google colab).
variable x untuk menampung kolom country, age, dan salary dan variable y untuk menampung kolom purchase

In [36]:
print (x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


disini masih ada missing value, kita akan isi missing valuenya

In [37]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [38]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

disini kita isi missing value nya dengan rata rata dari value kolom tersebut

In [39]:
print (x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


sehingga kolom kosong tadi atau missing value sudah terisi dengan rata rata dari value kolom tersebut

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder ='passthrough')
x = np.array(ct.fit_transform(x))

kita ubah kolom country menjadi matriks

In [43]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


french menjadi 1.0 0.0 0.0
spain menjadi 0.0 0.0 1.0
germany menjadi 0.0 1.0 0.0

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

kita ubah kolom label/purchase menjadi bentuk numerik

In [45]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


no = 0
yes = 1

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

kita bagi data menjadi data training dan data testing

In [47]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


x_train akan dapat 80% random value dari seluruh value variable x

In [48]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


x_test akan dapat 20% value dari varieble x

In [49]:
print(y_train)

[0 1 0 0 1 1 0 1]


y_train akan dapat 80% data label dari seluruh value variable y

In [50]:
print(y_test)

[0 1]


y_test akan dapat 20% data dari varieble y

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:, 3:])
x_test[:,3:] = sc.transform(x_test[:, 3:])

kita scale kolom age dan salary agar skala age dan salary tidak terlalu jauh 

In [52]:
print(x_train) 

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


sehingga hasil dari x_train seperti ini. skala age dan salary pada x_train menjadi lebih dekat

In [53]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


sehingga hasil dari x_test seperti ini. skala age dan salary pada x_test menjadi lebih dekat